apiVersion: securitytower.io/v1alpha1
kind: Application
metadata:
  name: agent-prometheus
spec:
  applicationOwner: syncier
  iconURL: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
  securityLevel: internal
  stages:
    - name: playground.cc
      cluster:
        repository: https://github.com/syncier/cluster-cc-playground.git
        name: playground
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: test-4.sbx
    - name: dev.cc
      cluster:
        repository: https://github.com/syncier/cluster-cc-dev.git
        name: dev
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: test-4.sbx
    - name: svc.cc
      cluster:
        repository: https://github.com/syncier/cluster-cc-svc.git
        name: svc
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: dev.cc
    - name: staging.apkv
      cluster:
        repository: https://github.com/syncier/cluster-apkv-staging.git
        name: staging
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: dev.apkv
    - name: prod.apkv
      cluster:
        repository: https://github.com/syncier/cluster-apkv-prod.git
        name: prod
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: staging.apkv
    - name: edithcare.staging.sda
      cluster:
        repository: https://github.com/syncier/cluster-sda-edithcare-staging.git
        name: staging
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: svc.cc
    - name: edithcare.prod.sda
      cluster:
        repository: https://github.com/syncier/cluster-sda-edithcare-prod.git
        name: prod
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: edithcare.staging.sda
    - name: svc.adh
      cluster:
        repository: https://github.com/syncier/cluster-adh-svc.git
        name: svc
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: dev.adh
    - name: dev.adh
      cluster:
        repository: https://github.com/syncier/cluster-adh-dev.git
        name: dev
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: svc.cc
    - name: staging.adh
      cluster:
        repository: https://github.com/syncier/cluster-adh-staging.git
        name: staging
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: svc.adh
    - name: prod.adh
      cluster:
        repository: https://github.com/syncier/cluster-adh-prod.git
        name: prod
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: staging.adh
    - name: dev.abs
      cluster:
        repository: https://github.com/syncier/cluster-abs-syc-dev.git
        name: dev
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: test-01.dev
    - name: dev.apkv
      cluster:
        repository: https://github.com/syncier/cluster-apkv-dev.git
        name: dev
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: svc.cc
    - name: prod.syc-sst
      cluster:
        repository: https://github.com/syncier/cluster-syc-sst-prod-cluster01.git
        name: prod-cluster01
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: test-01.dev
    - name: test-1.sbx
      cluster:
        repository: https://github.com/syncier/cluster-sbx-test1.git
        name: sbx-test-1
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
    - name: test-2.sbx
      cluster:
        repository: https://github.com/syncier/cluster-sbx-test2.git
        name: sbx-test-2
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: test-1.sbx
    - name: test-3.sbx
      cluster:
        repository: https://github.com/syncier/cluster-sbx-test3.git
        name: sbx-test-3
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: test-1.sbx
    - name: test-4.sbx
      cluster:
        repository: https://github.com/syncier/cluster-sbx-test4.git
        name: sbx-test-4
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: test-3.sbx
    - name: test-5.sbx
      cluster:
        repository: https://github.com/syncier/cluster-sbx-test5.git
        name: sbx-test-5
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: test-1.sbx
    - name: test-6.sbx
      cluster:
        repository: https://github.com/syncier/cluster-sbx-test6.git
        name: sbx-test-6
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: test-1.sbx
    - name: test-7.sbx
      cluster:
        repository: https://github.com/syncier/cluster-sbx-test7.git
        name: sbx-test-7
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: test-1.sbx
    - name: test-8.sbx
      cluster:
        repository: https://github.com/syncier/cluster-sbx-test8.git
        name: sbx-test-8
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: test-1.sbx
    - name: test-01.dev
      cluster:
        repository: https://github.com/syncier/cluster-syc-cloud-dev-test01.git
        name: test01
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: test-1.sbx
    - name: dev.analytics.grnry
      cluster:
        repository: https://github.com/syncier/cluster-dev-grnry-analytics.git
        name: analytics-grnry
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: test-01.dev
    - name: dev.analytics.abs
      cluster:
        repository: https://github.com/syncier/cluster-syc-analytics-dev-seceda01.git
        name: analytics-dev-seceda01
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: test-01.dev
    - name: prod.analytics.grnry
      cluster:
        repository: https://github.com/syncier/cluster-prod-grnry-analytics.git
        name: analytics-grnry-prod
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: dev.analytics.grnry
    - name: analytics.cc
      cluster:
        repository: https://github.com/syncier/cluster-cc-analytics.git
        name: analytics
      resources:
        revision: master
        path: cluster/namespaces/infra-monitoring/agent-prometheus
      targetNamespace: infra-monitoring
      previousStage: svc.cc
