apiVersion: securitytower.io/v1alpha1
kind: Application
metadata:
  name: istio-system-components
spec:
  applicationOwner: syncier
  iconURL: https://istio.io/latest/img/istio-whitelogo-bluebackground-framed.svg
  securityLevel: internal
  stages:
    - name: test-3.sbx
      cluster:
        repository: https://github.com/syncier/cluster-sbx-test3.git
        name: sbx-test-3
      resources:
        revision: master
        path: cluster/namespaces/istio-system
      targetNamespace: istio-system
