apiVersion: securitytower.io/v1alpha1
kind: Application
metadata:
  name: jenkins
spec:
  applicationOwner: syncier
  iconURL: https://www.jenkins.io/images/logos/jenkins/256.png
  securityLevel: internal
  stages:
    - name: dev.cc
      cluster:
        repository: https://github.com/syncier/cluster-cc-dev.git
        name: dev
      resources:
        revision: master
        path: cluster/namespaces/jenkins
      targetNamespace: jenkins
      previousStage: test-8.sbx
    - name: dev.adh
      cluster:
        repository: https://github.com/syncier/cluster-adh-dev.git
        name: dev
      resources:
        revision: master
        path: cluster/namespaces/jenkins
      targetNamespace: jenkins
      previousStage: dev.cc
    - name: test-8.sbx
      cluster:
        repository: https://github.com/syncier/cluster-sbx-test8.git
        name: sbx-test-8
      resources:
        revision: master
        path: cluster/namespaces/jenkins
      targetNamespace: jenkins
    - name: analytics.cc
      cluster:
        repository: https://github.com/syncier/cluster-cc-analytics.git
        name: analytics
      resources:
        revision: master
        path: cluster/namespaces/jenkins
      targetNamespace: jenkins
      previousStage: dev.cc
