apiVersion: securitytower.io/v1alpha1
kind: Application
metadata:
  name: loki
spec:
  applicationOwner: syncier
  iconURL: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png
  securityLevel: internal
  stages:
    - name: prod.syc-sst
      cluster:
        repository: https://github.com/syncier/cluster-syc-sst-prod-cluster01.git
        name: prod-cluster01
      resources:
        revision: master
        path: cluster/namespaces/loki
      targetNamespace: loki
